apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
      - name: shared-image
        persistentVolumeClaim:
          claimName: ping-pong-claim
      containers:
      - name: ping-pong
        image: iritmaximus/ping-pong@sha256:c6ca6be7b1fd066a691b284f2e512f626ea766bb79efba23fab15773ceda4152
        volumeMounts:
        - name: shared-image
          mountPath: /usr/src/app/files
        env:
        - name: PORT
          value: "4000"
