apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: todo
        image: iritmaximus/ping-pong@sha256:cac69c1c15dc1bec5a8ee4abb3bdd7f7058fb2dcbe6025722ef0909ecddb3441
        env:
        - name: PORT
          value: "4000"
