apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: iritmaximus/todo@sha256:96b6035e5fcf83fe8048259cd1cdcb33c218d7c63e6c159b020bd182227c16c7
        env:
        - name: PORT
          value: "5000"
