apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: iritmaximus/todo@sha256:1238622156035652fee0d987328dead0087056d1991af4479ae7ce8ae49d79bb
        env:
        - name: PORT
          value: "5000"
