apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-image
        persistentVolumeClaim:
          claimName: ping-pong-claim
      containers:
      - name: log-output-server
        image: iritmaximus/log-output-server@sha256:272a790c1f3793535187159c26b8864e7bbfe0c5b69c3b6383c2ab47a3522d8d
        volumeMounts:
        - name: shared-image
          mountPath: /usr/src/app/files
        env:
        - name: PORT
          value: "3002"
      - name: log-output-file
        image: iritmaximus/log-output-file@sha256:8718553424a9bf57329ab145441a98545960027807a50a92c677bee6e1e59bf1
        volumeMounts:
        - name: shared-image
          mountPath: /usr/src/app/files
