apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: shared-image
        persistentVolumeClaim:
          claimName: dwk-claim
      containers:
      - name: log-output-server
        image: iritmaximus/log-output-server@sha256:8d06b31845da80c053be32c86c3ebbae7be1818e453891bbc8f531eef1611e5e
        volumeMounts:
        - name: shared-image
          mountPath: /usr/src/app/files
        env:
        - name: PORT
          value: "3002"
      - name: log-output-file
        image: iritmaximus/log-output-file@sha256:ab4f976c14dd70483d3e7bc1e013b513ad592f88867a5c98295328c81d139f38
        volumeMounts:
        - name: shared-image
          mountPath: /usr/src/app/files
