apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: iritmaximus/log-output-server@sha256:4d993959dbc3cab1e42f5572259626bd204207558cdc24e91b1808e6a2b769fe
          env:
          - name: PORT
            value: "3002"
